
```{r}
library(tidyverse)
library(tidymodels)
library(mice) 
library(VIM) 
library(rpart) 
library(rpart.plot)
library(RColorBrewer) 
library(rattle)
library(caret)
```

```{r}
heart = heart_disease_1 %>% mutate(Sex = as_factor(Sex)) %>% 
  mutate(ChestPainType = as_factor(ChestPainType))%>% 
  mutate(RestingECG = as_factor(RestingECG))%>% 
  mutate(ExerciseAngina = as_factor(ExerciseAngina))%>% 
  mutate(ST_Slope = as_factor(ST_Slope))%>% 
  mutate(HeartDisease = as_factor(HeartDisease))%>% 
  mutate(HeartDisease = fct_recode(HeartDisease, "No" = "0", "Yes" = "1" ))
nrow(heart)
```
```{r}
set.seed(12345) 
heart_split = initial_split(heart, prop = 0.7, strata = HeartDisease)
train = training(heart_split) 
test = testing(heart_split)
nrow(train)
```

```{r}
heart_recipe = recipe(HeartDisease ~ Sex + ChestPainType + RestingECG + ExerciseAngina + ST_Slope, train)

tree_model = decision_tree() %>% 
  set_engine("rpart", model = TRUE) %>% 
  set_mode("classification")

heart_wflow = 
  workflow() %>% 
  add_model(tree_model) %>% 
  add_recipe(heart_recipe)

heart_fit = fit(heart_wflow, train)
```

```{r}
tree = heart_fit %>% 
  pull_workflow_fit() %>% 
  pluck("fit")

rpart.plot(tree)
```

```{r}
heart_fit$fit$fit$fit$cptable
```

```{r}
set.seed(123)
folds = vfold_cv(train, v = 5)

heart_recipe = recipe(HeartDisease ~ Sex + ChestPainType + RestingECG + ExerciseAngina + ST_Slope, train) %>%
  step_dummy(all_nominal(),-all_outcomes())

tree_model = decision_tree(cost_complexity = tune()) %>% 
  set_engine("rpart", model = TRUE) %>% 
  set_mode("classification")

tree_grid = grid_regular(cost_complexity(),
                          levels = 25) 

heart_wflow = 
  workflow() %>% 
  add_model(tree_model) %>% 
  add_recipe(heart_recipe)

tree_res = 
  heart_wflow %>% 
  tune_grid(resamples = folds,grid = tree_grid)

tree_res
```

```{r}
options(scipen=999)
tree_res %>%
  collect_metrics() %>%
  ggplot(aes(cost_complexity, mean)) +
  geom_line(size = 1.5, alpha = 0.6) +
  geom_point(size = 2) +
  facet_wrap(~ .metric, scales = "free", nrow = 2) 
```

```{r}
best_tree = tree_res %>%
  select_best("accuracy")

best_tree
```
```{r}
str(heart)
summary(heart)
```

```{r}
final_wf = 
  heart_wflow %>% 
  finalize_workflow(best_tree)
```

```{r}
final_fit = fit(final_wf, train)

tree = final_fit %>% 
  pull_workflow_fit() %>% 
  pluck("fit")

fancyRpartPlot(tree, tweak = 1.5) 
```

```{r}
treepred = predict(final_fit, train)
head(treepred)
confusionMatrix(treepred$.pred_class,train$HeartDisease,positive="Yes")
```

```{r}
treepred_test = predict(final_fit, test, type = "class")
head(treepred_test)
confusionMatrix(treepred_test$.pred_class,test$HeartDisease,positive="Yes")
```

```{r}
heart_recipe = recipe(HeartDisease ~., train) %>% 
  step_dummy(all_nominal(),-all_outcomes())

tree_model = decision_tree(cost_complexity = tune()) %>% 
  set_engine("rpart", model = TRUE) %>% 
  set_mode("classification")

tree_grid = expand.grid(cost_complexity = seq(0.001,0.01,by=0.001))

heart_wflow = 
  workflow() %>% 
  add_model(tree_model) %>% 
  add_recipe(heart_recipe)

tree_res = 
  heart_wflow %>% 
  tune_grid(
    resamples = folds,
    grid = tree_grid
    )

tree_res
```

```{r}
tree_res %>%
  collect_metrics() %>%
  ggplot(aes(cost_complexity, mean)) +
  geom_line(size = 1.5, alpha = 0.6) +
  geom_point(size = 2) +
  facet_wrap(~ .metric, scales = "free", nrow = 2) 
```

```{r}
final_wf = 
  heart_wflow %>% 
  finalize_workflow(best_tree)
```


```{r}
final_fit = fit(final_wf, train)

tree = final_fit %>% 
  pull_workflow_fit() %>% 
  pluck("fit")

fancyRpartPlot(tree, tweak = 1.5) 
```
```{r}
treepred = predict(final_fit, train)
head(treepred)
confusionMatrix(treepred$.pred_class,train$HeartDisease,positive="Yes")
```

